# Generated by Django 4.0.4 on 2022-04-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='json_data',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
