# Generated by Django 4.0.4 on 2022-04-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_lobby_json_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=120)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_hero_index', models.IntegerField(default=0)),
                ('n', models.IntegerField(default=22)),
                ('m', models.IntegerField(default=26)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hero', max_length=30)),
                ('eng_name', models.CharField(default='Hero', max_length=30)),
                ('i', models.IntegerField(default=0)),
                ('j', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('global_index', models.IntegerField(default=0)),
                ('team', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
                ('attacks_during_turn', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hp', models.IntegerField(default=0)),
                ('max_energy', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('magic', models.IntegerField(default=0)),
                ('attack_range', models.FloatField(default=0)),
                ('attack_cost', models.IntegerField(default=0)),
                ('slowdown', models.IntegerField(default=0)),
                ('solidity', models.BooleanField(default=False)),
                ('can_autoattack', models.BooleanField(default=True)),
                ('stun', models.BooleanField(default=False)),
                ('toxicity_value', models.IntegerField(default=0)),
                ('toxicity_duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='json_data',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cooldown', models.IntegerField(default=1)),
                ('cur_cooldown', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=1)),
                ('chosen', models.BooleanField(default=False)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Main.hero')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='base_params',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='base_hero', to='Main.heroparams'),
        ),
        migrations.AddField(
            model_name='hero',
            name='game_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_heroes', to='Main.gamestate'),
        ),
        migrations.AddField(
            model_name='hero',
            name='params',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hero', to='Main.heroparams'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='game_state',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lobby', to='Main.gamestate'),
        ),
    ]
