# Generated by Django 4.0.4 on 2022-04-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_eventlog_gamestate_hero_heroparams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='max_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='max_hp',
            field=models.IntegerField(default=0),
        ),
    ]
