# Generated by Django 4.0.4 on 2022-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_hero_max_energy_remove_hero_max_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroparams',
            name='silence',
            field=models.BooleanField(default=False),
        ),
    ]
