# Generated by Django 4.0.4 on 2022-05-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_heroparams_silence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='m',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='n',
            field=models.IntegerField(default=12),
        ),
    ]
