# Generated by Django 4.0.4 on 2022-05-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_gamestate_m_alter_gamestate_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.IntegerField()),
                ('type', models.CharField(choices=[('damage', 'damage'), ('redraw', 'redraw')], max_length=10)),
                ('target_id', models.IntegerField()),
                ('duration', models.FloatField(default=0.3)),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='update_id',
            field=models.IntegerField(default=1),
        ),
    ]
