# Generated by Django 4.0.4 on 2022-05-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_uiaction_gamestate_update_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiaction',
            name='game_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Main.gamestate'),
            preserve_default=False,
        ),
    ]
