# Generated by Django 4.0.4 on 2022-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_uiaction_game_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uiaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='uiaction',
            name='update_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
