# Generated by Django 4.0.4 on 2022-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_remove_uiaction_id_alter_uiaction_update_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiaction',
            name='target_id',
            field=models.IntegerField(default=0),
        ),
    ]
