# Generated by Django 4.0.4 on 2022-05-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_circle_line_rectangle_skill_phase_marksrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksrule',
            name='game_state',
            field=models.ForeignKey(default=53, on_delete=django.db.models.deletion.CASCADE, to='Main.gamestate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marksrule',
            name='name',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
