# Generated by Django 4.0.4 on 2022-05-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_skill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='active_hero_json',
            field=models.TextField(default='{}', max_length=100),
        ),
    ]
