# Generated by Django 4.0.4 on 2022-05-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Main', '0015_gamestate_active_hero_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alive', models.BooleanField(default=True)),
                ('duration', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.PositiveIntegerField()),
                ('caster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_effects', to='Main.hero')),
                ('effect_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='Main.hero')),
            ],
        ),
    ]
