# Generated by Django 4.0.4 on 2022-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_poison_effectlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poison',
            name='is_alive',
        ),
        migrations.AddField(
            model_name='effectlink',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
