# Generated by Django 4.0.4 on 2022-05-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_remove_poison_is_alive_effectlink_is_alive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bleeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
