# Generated by Django 4.0.4 on 2022-05-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_bleeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=15)),
                ('value', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('is_alive', models.BooleanField(default=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='Main.hero')),
            ],
        ),
    ]
