# Generated by Django 4.0.4 on 2022-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_slowdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='modifier',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
    ]
