# Generated by Django 4.0.4 on 2022-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_stun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toxicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('value', models.IntegerField()),
                ('poison_duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
