# Generated by Django 4.0.4 on 2022-06-11 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Main', '0024_silence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('stun_cancel', models.BooleanField(default=False)),
                ('move_cancel', models.BooleanField(default=False)),
                ('max_distance', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DelayedDamage_Effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_id', models.PositiveIntegerField()),
                ('delayed_damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dd_effects', to='Main.delayeddamage')),
                ('effect_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
