# Generated by Django 4.0.4 on 2022-06-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_delayeddamage_delayeddamage_effects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='i',
            new_name='_i',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='j',
            new_name='_j',
        ),
    ]
