# Generated by Django 4.0.4 on 2022-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_rename_i_hero__i_rename_j_hero__j'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayeddamage',
            name='end_function_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
