# Generated by Django 4.0.4 on 2022-08-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_remove_gamestate_m_remove_gamestate_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('team', models.IntegerField()),
                ('number', models.IntegerField()),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towers', to='Main.gamestate')),
            ],
        ),
    ]
