# Generated by Django 4.0.4 on 2022-09-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_tower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_i', models.IntegerField(default=0)),
                ('_j', models.IntegerField(default=0)),
                ('team', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
                ('attacks_during_turn', models.IntegerField(default=0)),
                ('is_alive', models.BooleanField(default=True)),
                ('base_params', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='base_minion', to='Main.heroparams')),
                ('game_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_minions', to='Main.gamestate')),
                ('params', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='minion', to='Main.heroparams')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
