# Generated by Django 4.0.4 on 2023-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_minion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiaction',
            name='update_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
