# Generated by Django 4.0.4 on 2022-04-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsys', '0002_userprofile_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.IntegerField(default=0),
        ),
    ]
